{
 "title": "CurrencyConvertor",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "from(bucket: \"myBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rates_request\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_code\")\n  |> filter(fn: (r) => r._value >= 200 and r._value < 300)\n  |> aggregateWindow(every: 1s, fn: count)  // Aggregate counts per second\n  |> map(fn: (r) => ({r with _field: \"2xx requests\"}))"
    },
    {
     "query": "from(bucket: \"myBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rates_request\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_code\")\n  |> filter(fn: (r) => r._value >= 400 and r._value < 500)\n  |> aggregateWindow(every: 1s, fn: count)  // Aggregate counts per second\n  |> map(fn: (r) => ({r with _field: \"4xx requests\"}))"
    },
    {
     "query": "from(bucket: \"myBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rates_request\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_code\")\n  |> filter(fn: (r) => r._value >= 500)\n  |> aggregateWindow(every: 1s, fn: count)  // Aggregate counts per second\n  |> map(fn: (r) => ({r with _field: \"5xx requests\"}))\n  "
    }
   ]
  },
  {
   "title": "Swop API health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "from(bucket: \"myBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swop_api_call\")\n  |> filter(fn: (r) => r[\"_field\"] == \"success\")\n  |> filter(fn: (r) => r._value == true)\n  |> aggregateWindow(every: 1s, fn: count)  // Aggregate counts per second\n  |> map(fn: (r) => ({r with _field: \"OK\"}))"
    },
    {
     "query": "from(bucket: \"myBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swop_api_call\")\n  |> filter(fn: (r) => r[\"_field\"] == \"success\")\n  |> filter(fn: (r) => r._value == false)\n  |> aggregateWindow(every: 1s, fn: count)  // Aggregate counts per second\n  |> map(fn: (r) => ({r with _field: \"Failed\"}))"
    }
   ]
  },
  {
   "title": "Cache hit % (last 1h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $swop_api_calls / $all_requests",
     "type": "math"
    }
   ]
  }
 ]
}